/* SPDX-License-Identifier: GPL-3.0-or-later */
/* Copyright © 2026 Eduard Smet */

@since(version = 0.1.0)
interface core-types {
    @since(version = 0.1.0)
    enum log-levels {
        trace,
        debug,
        info,
        warn,
        error,
    }
}
