/* SPDX-License-Identifier: GPL-3.0-or-later */
/* Copyright © 2026 Eduard Smet */

interface core-types {
    type json = string;

    type host-error = string;

    type plugin-error = string;
}

interface core-import-types {
    use core-types.{host-error};

    // Services
    use job-scheduler-import-types.{job-scheduler-registrations, job-scheduler-registrations-result, job-scheduler-deregistrations, job-scheduler-deregistrations-result};
    use discord-import-types.{discord-registrations, discord-registrations-result, discord-deregistrations, discord-deregistrations-result};

    enum log-levels {
        trace,
        debug,
        info,
        warn,
        error,
    }

    record registrations {
        core: option<core-registrations>,
        services: option<services-registrations>,
    }

    record core-registrations {
        dependency-functions: option<list<string>>,
    }

    record services-registrations {
        job-scheduler: option<job-scheduler-registrations>,
        discord: option<discord-registrations>,
    }

    record registrations-result {
        core: option<core-registrations-result>,
        services: option<services-registrations-result>,
    }

    record core-registrations-result {
        dependency-functions: option<result<map<string, string>, host-error>>,
    }

    record services-registrations-result {
        job-scheduler: option<result<job-scheduler-registrations-result, host-error>>,
        discord: option<result<discord-registrations-result, host-error>>
    }

    record deregistrations {
        core: option<core-deregistrations>,
        services: option<services-deregistrations>,
    }

    record core-deregistrations {
        dependency-functions: option<list<string>>
    }

    record services-deregistrations {
        job-scheduler: option<job-scheduler-deregistrations>,
        discord: option<discord-deregistrations>,
    }

    record deregistrations-result {
        core: option<core-deregistrations-result>,
        services: option<services-deregistrations-result>,
    }

    record core-deregistrations-result {
        dependency-functions: option<list<string>>
    }

    record services-deregistrations-result {
        job-scheduler: option<result<job-scheduler-deregistrations-result, host-error>>,
        discord: option<result<discord-deregistrations-result, host-error>>,
    }
}

interface core-import-functions {
    use core-types.{host-error};
    use core-import-types.{deregistrations, deregistrations-result, log-levels, registrations, registrations-result};


    register: func(registrations: registrations) -> registrations-result;
    deregister: func(deregistrations: deregistrations) -> deregistrations-result;

    log: func(level: log-levels, message: string);

    get-state: func(key: string) -> result<option<list<u8>>, host-error>;
    set-state: func(key: string, value: list<u8>) -> result<_, host-error>;
    clear-state: func() -> result<_, host-error>;

    dependency-function: func(registry-id: string, plugin-id: string, function-id: string, plugin-version: option<string>, params: list<u8>) -> result<list<u8>, host-error>;

    remove: func(reason: string);
    shutdown: func(restart: bool) -> result<_, host-error>;
}

interface core-export-functions {
    use core-types.{json, plugin-error};

    initialization: func(settings: json) -> result<_, plugin-error>;

    dependency-function: func(function-id: string, params: list<u8>) -> result<list<u8>, plugin-error>;

    shutdown: func() -> result<_, plugin-error>;
}

