/* SPDX-License-Identifier: GPL-3.0-or-later */
/* Copyright © 2026 Eduard Smet */

interface discord-types {
    type snowflake = u64;
}

interface discord-import-types {
    use core-types.{host-error, json};
    use discord-types.{snowflake};

    enum discord-event-kinds {
        message-create,
        interaction-create,
        thread-create,
        thread-delete,
        thread-list-sync,
        thread-member-update,
        thread-members-update,
        thread-update,
    }

    // Registrations
    record discord-registrations {
        events: option<discord-registrations-events>,
        interactions: option<discord-registrations-interactions>,
    }

    type discord-registrations-events = list<discord-event-kinds>;

    record discord-registrations-interactions {
        application-commands: option<list<json>>,
        message-components: option<u16>,
        modals: option<u16>,
    }

    // Registrations Result
    record discord-registrations-result {
        events: option<discord-registrations-events-result>,
        interactions: option<discord-registrations-interactions-result>,
    }

    // Map keys can only be component model primitives
    type discord-registrations-events-result = list<tuple<discord-event-kinds, result<_, host-error>>>;

    record discord-registrations-interactions-result {
        application-commands: option<result<_, host-error>>,
        message-components: option<result<list<string>, host-error>>,
        modals: option<result<list<string>, host-error>>,
    }

    // Deregistrations
    record discord-deregistrations {
        events: option<discord-deregistrations-events>,
        interactions: option<discord-deregistrations-interactions>,
    }

    type discord-deregistrations-events = list<discord-event-kinds>;

    record discord-deregistrations-interactions {
        application-commands: option<list<string>>,
        message-components: option<list<string>>,
        modals: option<list<string>>,
    }

    // Deregistrations Result
    record discord-deregistrations-result {
        events: option<discord-deregistrations-events-result>,
        interactions: option<discord-deregistrations-interactions-result>
    }

    type discord-deregistrations-events-result = list<tuple<discord-event-kinds, result<_, host-error>>>;

    record discord-deregistrations-interactions-result {
        application-commands: option<result<list<string>, host-error>>,
        message-components: option<result<list<string>, host-error>>,
        modals: option<result<list<string>, host-error>>,
    }

    // Discord Requests
    variant discord-requests {
        // Gateway commands
        request-guild-members(tuple<snowflake, json>),
        request-soundboard-sounds(list<snowflake>),
        update-voice-state(tuple<snowflake, json>),
        update-presence(json),

        // HTTP operations
        add-thread-member(tuple<snowflake, snowflake>),
        create-ban(tuple<snowflake, snowflake, json>),
        create-forum-thread(tuple<snowflake, body>),
        create-message(tuple<snowflake, body>),
        create-thread(tuple<snowflake, json>),
        create-thread-from-message(tuple<snowflake, snowflake, json>),
        delete-message(tuple<snowflake, snowflake>),
        get-active-threads(snowflake),
        get-channel(snowflake),
        get-joined-private-archived-threads(tuple<option<snowflake>, snowflake, option<snowflake>>),
        get-private-archived-threads(tuple<option<string>, snowflake, option<snowflake>>),
        get-public-archived-threads(tuple<option<string>, snowflake, option<snowflake>>),
        get-thread-member(tuple<snowflake, snowflake>),
        get-thread-members(tuple<option<snowflake>, snowflake, option<u32>, option<bool>>),
        interaction-callback(tuple<snowflake, string, bool, json>),
        join-thread(snowflake),
        leave-thread(snowflake),
        remove-thread-member(tuple<snowflake, snowflake>),
        update-member(tuple<snowflake, snowflake, json>),
        update-interaction-original(tuple<snowflake, string, json>),
    }

    variant body {
        json(json),
        form(form),
    }

    type form = list<u8>;

    // Discord Responses
    type discord-responses = json;
}

interface discord-export-types {
    use core-types.{json, plugin-error};
    use discord-types.{snowflake};

    // Discord Application Command Registrations Result
    type discord-registrations-result-application-commands = map<string, result<snowflake, plugin-error>>;

    // Discord Events
    variant discord-events {
        interaction-create(json),
        message-create(json),
        thread-create(json),
        thread-delete(json),
        thread-list-sync(json),
        thread-member-update(json),
        thread-members-update(json),
        thread-update(json),
    }
}

interface discord-import-functions {
    use core-types.{host-error};
    use discord-import-types.{discord-requests, discord-responses};

    discord-request: func(request: discord-requests) -> result<option<discord-responses>, host-error>;
}

interface discord-export-functions {
    use core-types.{plugin-error};
    use discord-export-types.{discord-events, discord-registrations-result-application-commands};

    discord-application-commands: func(registrations-result: discord-registrations-result-application-commands);

    discord-event: func(event: discord-events) -> result<_, plugin-error>;
}
