/* SPDX-License-Identifier: GPL-3.0-or-later */
/* Copyright © 2026 Eduard Smet */

interface job-scheduler-import-types {
    use core-import-types.{error};

    flags supported-job-scheduler-registrations {
        scheduled-jobs,
    }

    /// All registrations are opt in.
    ///
    /// The `scheduled-jobs` field list entries should exist out of cron values.
    ///
    /// cron: https://en.wikipedia.org/wiki/Cron
    record job-scheduler-registrations {
        scheduled-jobs: list<string>,
    }

    /// TODO: Rewrite docs
    /// The `scheduled-jobs` field returns separate lists of successful and failed cron values.
    record job-scheduler-registrations-result {
        scheduled-jobs: result<list<tuple<string, result<string, error>>>, error>,
    }

    record job-scheduler-deregistrations {
        scheduled-jobs: list<string>,
    }

    record job-scheduler-deregistrations-result {
        scheduled-jobs: list<tuple<string, result<_, error>>>,
    }

}

interface job-scheduler-export-types {

}

interface job-scheduler-import-functions {
    use core-import-types.{error};
    use job-scheduler-import-types.{job-scheduler-deregistrations, job-scheduler-deregistrations-result, job-scheduler-registrations, job-scheduler-registrations-result, supported-job-scheduler-registrations};

    get-supported-registrations: func() -> supported-job-scheduler-registrations;
    register: func(registrations: job-scheduler-registrations) -> job-scheduler-registrations-result;
    deregister: func(deregistrations: job-scheduler-deregistrations) -> job-scheduler-deregistrations-result;
}

interface job-scheduler-export-functions {
    use core-export-types.{error};

    scheduled-job: func(job-id: string) -> result<_, error>;
}
