/* SPDX-License-Identifier: GPL-3.0-or-later */
/* Copyright © 2026 Eduard Smet */

interface job-scheduler-import-types {
    use core-types.{host-error};

    record job-scheduler-registrations {
        scheduled-jobs: option<list<string>>,
    }

    record job-scheduler-registrations-result {
        scheduled-jobs: option<result<map<string, result<string, host-error>>, host-error>>,
    }

    record job-scheduler-deregistrations {
        scheduled-jobs: option<list<string>>,
    }

    record job-scheduler-deregistrations-result {
        scheduled-jobs: option<map<string, result<_, host-error>>>,
    }
}

interface job-scheduler-export-functions {
    use core-types.{plugin-error};

    scheduled-job: func(job-id: string) -> result<_, plugin-error>;
}
