/* SPDX-License-Identifier: GPL-3.0-or-later */
/* Copyright © 2026 Eduard Smet */

package wpbs:plugin@0.1.0;

world plugin {
    import core-import-functions;
    export core-export-functions;

    export job-scheduler-export-functions;

    import discord-import-functions;
    export discord-export-functions;
}
