FROM alpine:latest AS certs
RUN apk --no-cache add ca-certificates

FROM scratch

COPY --from=certs /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/

ARG TARGETARCH

COPY bin/${TARGETARCH}/wpbs /wpbs

COPY LICENSE README.md ./

CMD ["/wpbs"]
