/* SPDX-License-Identifier: GPL-3.0-or-later */
/* Copyright © 2026 Eduard Smet */

use wpbs:shared/shared-types@0.1.0;

@since(version = 0.1.0)
interface job-scheduler-types {
    use shared-types.{host-error};

    @since(version = 0.1.0)
    type cron = string;

    @since(version = 0.1.0)
    type registrations = list<cron>;

    @since(version = 0.1.0)
    type registrations-result = map<string, result<_, host-error>>;

    @since(version = 0.1.0)
    type deregistrations = list<cron>;

    @since(version = 0.1.0)
    type deregistrations-result = map<string, result<_, host-error>>;
}
