/* SPDX-License-Identifier: GPL-3.0-or-later */
/* Copyright © 2026 Eduard Smet */

package wpbs-services:job-scheduler@0.1.0;

use wpbs:shared/shared-types@0.1.0;

@since(version = 0.1.0)
world job-scheduler {
    @since(version = 0.1.0)
    import job-scheduler-import-functions;
    @since(version = 0.1.0)
    export job-scheduler-export-functions;
}

@since(version = 0.1.0)
interface job-scheduler-import-functions {
    use job-scheduler-types.{deregistrations, deregistrations-result, registrations, registrations-result};
    use shared-types.{host-error};

    @since(version = 0.1.0)
    register: func(registrations: registrations) -> result<registrations-result, host-error>;
    @since(version = 0.1.0)
    deregister: func(deregistrations: deregistrations) -> result<deregistrations-result, host-error>;
}

@since(version = 0.1.0)
interface job-scheduler-export-functions {
    use job-scheduler-types.{cron};
    use shared-types.{plugin-error, uuid};

    @since(version = 0.1.0)
    scheduled-job: func(cron: cron) -> result<_, plugin-error>;
}
